name: Release Workflow
 
on:
  push:
   tags:
      - 'v*'
   paths-ignore: 
     - '.github/**'
     
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Build Artifacts
        id: buildApks
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: app:bundleRelease

      - name: Clean up build artifacts
        run: |
          cp app/build/outputs/bundle/release/app-release.aab app-release.aab
      - uses: actions/upload-artifact@v3
        with:
          name: Uploading App
          path: app-release.aab
